# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='', verbose_name=1000),
        ),
    ]
